[package]

name = "pitch_calc"
description = "A library for musical pitch conversions! Provides functions and methods for converting between frequency, midi-step and letter-octave."
version = "0.8.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
readme = "README.md"
keywords = ["pitch", "dsp", "audio", "music", "conversion"]
license = "Apache-2.0/MIT"

[dependencies]
rustc-serialize = "0.1.1"
